parameters:
    varnish.data_fetcher.class: AssignmentBundle\Service\DataFetcher
    varnish.source_url: http://tech.vg.no/intervjuoppgave/varnish.log
    varnish.data_formatter.class: AssignmentBundle\Model\VarnishFormatter
    varnish.log_parser.class: Kassner\LogParser\LogParser
    varnish.log_format: '%%h %%l %%u %%t "%%r" %%>s %%O "%%{Referer}i" \"%%{User-Agent}i"'