services:
    varnish.data_fetcher:
        class: %varnish.data_fetcher.class%
        arguments: ['%varnish.source_url%', '@varnish.formatter']
    varnish.formatter:
        class: %varnish.data_formatter.class%
