services:
    # varnish-log
    varnish.domain_data_fetcher:
        class: %varnish.data_fetcher.class%
        arguments: ['%varnish.source_url%', '@varnish.domain_formatter']
    varnish.file_data_fetcher:
        class: %varnish.data_fetcher.class%
        arguments: ['%varnish.source_url%', '@varnish.file_formatter']
    varnish.domain_formatter:
        class: %varnish.domain_formatter.class%
        arguments: ['@varnish.log_parser_wrapper', %varnish.limit%]
    varnish.file_formatter:
        class: %varnish.file_formatter.class%
        arguments: ['@varnish.log_parser_wrapper', %varnish.limit%]
    varnish.log_parser_wrapper:
        class: %varnish.log_parser.class%
        # Set nginx-format.
        calls:
            - [setFormat, [%varnish.log_format%]]
    # article-rss
    article.rss_data_fetcher:
        class: %article.data_fetcher.class%
        arguments: ['%article.source_url%', '@article.rss_formatter']
    article.rss_formatter:
        class: %article.rss_formatter.class%
    # json-source
    json_data_fetcher:
        class: %json.data_fetcher.class%
        arguments: ['%json.source_url%', '@json.formatter']
    json.formatter:
        class: %json.formatter.class%